---
name: Getopt-CallingName
version: 1.12
author: []
abstract: Script duties delegation based upon calling name
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Getopt::CallingName:
    file: lib/Getopt/CallingName.pm
    version: 1.12
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
